export interface PropertyDtoTemp {
  id: number;
  name: string;
  address: string;
  price: number;
  bedrooms: number;
  bathrooms: number;
  sqft: number;
  image: string;
  features: string[];
  description: string;
  yearBuilt: number;
  lotSize: number;
  propertyType: string;
  gallery: string[];
  featured: boolean;
}

export const properties: PropertyDtoTemp[] = [
  {
    id: 1,
    name: "The Meridian Estate",
    address: "1847 Pacific Heights Boulevard, San Francisco, CA",
    price: 8750000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    image: "/luxury-modern-mansion-pool.png",
    features: ["Ocean View", "Wine Cellar", "Home Theater"],
    description:
      "An architectural masterpiece perched atop Pacific Heights, The Meridian Estate offers breathtaking panoramic views of the San Francisco Bay and Golden Gate Bridge. This stunning contemporary residence features floor-to-ceiling windows, a gourmet chef's kitchen with top-of-the-line appliances, and a luxurious master suite with spa-like bathroom. The lower level boasts an impressive wine cellar, state-of-the-art home theater, and fitness center. Outdoor living spaces include multiple terraces, an infinity pool, and meticulously landscaped gardens.",
    yearBuilt: 2020,
    lotSize: 12000,
    propertyType: "Single Family Home",
    gallery: [
      "/luxury-modern-mansion-pool.png",
      "/luxury-estate-with-gardens.jpg",
      "/luxury-penthouse-city-view.jpg",
    ],
    featured: true,
  },
  {
    id: 2,
    name: "Belmont Manor",
    address: "2156 Sunset Ridge Drive, Beverly Hills, CA",
    price: 12500000,
    bedrooms: 8,
    bathrooms: 10,
    sqft: 12000,
    image: "/luxury-estate-with-gardens.jpg",
    features: ["Tennis Court", "Guest House", "Infinity Pool"],
    description:
      "Belmont Manor is a grand estate that epitomizes luxury living in Beverly Hills. Set on over 2 acres of pristine grounds, this magnificent property features a main residence with soaring ceilings, formal living and dining rooms, and a chef's kitchen that opens to family room. The expansive master wing includes dual bathrooms, walk-in closets, and private terrace. Additional amenities include a separate guest house, professional tennis court, resort-style infinity pool with cabana, and beautifully manicured gardens with mature trees.",
    yearBuilt: 2018,
    lotSize: 87000,
    propertyType: "Estate",
    gallery: [
      "/luxury-estate-with-gardens.jpg",
      "/luxury-modern-mansion-pool.png",
      "/beachfront-luxury-villa.jpg",
    ],
    featured: false,
  },
  {
    id: 3,
    name: "Skyline Penthouse",
    address: "432 Park Avenue, New York, NY",
    price: 15000000,
    bedrooms: 5,
    bathrooms: 6,
    sqft: 6800,
    image: "/luxury-penthouse-city-view.jpg",
    features: ["360° Views", "Private Elevator", "Rooftop Terrace"],
    description:
      "Experience unparalleled luxury in this extraordinary penthouse offering 360-degree views of Manhattan's iconic skyline. Accessible via private elevator, this residence features floor-to-ceiling windows, custom millwork throughout, and the finest finishes. The open-concept living space flows seamlessly to a gourmet kitchen with premium appliances. The master suite is a true sanctuary with panoramic views, spa bathroom, and custom closets. The crown jewel is the private rooftop terrace with outdoor kitchen, perfect for entertaining while taking in breathtaking city views.",
    yearBuilt: 2019,
    lotSize: 6800,
    propertyType: "Penthouse",
    gallery: [
      "/luxury-penthouse-city-view.jpg",
      "/luxury-modern-mansion-pool.png",
      "/luxury-estate-with-gardens.jpg",
    ],
    featured: true,
  },
  {
    id: 4,
    name: "Oceanfront Villa",
    address: "789 Coastal Highway, Malibu, CA",
    price: 9800000,
    bedrooms: 5,
    bathrooms: 6,
    sqft: 7200,
    image: "/beachfront-luxury-villa.jpg",
    features: ["Private Beach", "Spa", "Smart Home"],
    description:
      "This stunning oceanfront villa offers the ultimate in coastal luxury living. Situated on a rare stretch of private beach, the residence features walls of glass that frame spectacular ocean views. The open floor plan includes a chef's kitchen, formal dining room, and multiple living areas that flow to expansive decks. The master suite occupies the entire upper level with ocean-view terrace and luxurious spa bathroom. Additional features include a home spa with sauna and steam room, smart home technology, and direct beach access.",
    yearBuilt: 2021,
    lotSize: 15000,
    propertyType: "Villa",
    gallery: [
      "/beachfront-luxury-villa.jpg",
      "/luxury-modern-mansion-pool.png",
      "/luxury-lakefront-home.jpg",
    ],
    featured: false,
  },
  {
    id: 5,
    name: "The Grandview Residence",
    address: "1523 Mountain Peak Lane, Aspen, CO",
    price: 11200000,
    bedrooms: 7,
    bathrooms: 8,
    sqft: 9500,
    image: "/luxury-mountain-chalet.png",
    features: ["Ski-in/Ski-out", "Wine Room", "Heated Driveway"],
    description:
      "The Grandview Residence is a spectacular mountain retreat offering true ski-in/ski-out access. This architectural gem combines rustic elegance with modern luxury, featuring soaring ceilings with exposed beams, stone fireplaces, and walls of windows showcasing mountain views. The gourmet kitchen is a chef's dream, while the great room provides the perfect gathering space. The luxurious master suite includes a fireplace and spa bathroom. Additional amenities include a wine room, home theater, heated driveway, and multiple outdoor living spaces with hot tub.",
    yearBuilt: 2019,
    lotSize: 18000,
    propertyType: "Mountain Home",
    gallery: [
      "/luxury-mountain-chalet.png",
      "/luxury-estate-with-gardens.jpg",
      "/luxury-modern-mansion-pool.png",
    ],
    featured: true,
  },
  {
    id: 6,
    name: "Lakeside Sanctuary",
    address: "456 Lakeshore Drive, Lake Tahoe, NV",
    price: 7500000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8000,
    image: "/luxury-lakefront-home.jpg",
    features: ["Private Dock", "Boat House", "Outdoor Kitchen"],
    description:
      "Lakeside Sanctuary is a stunning waterfront estate offering 200 feet of pristine lakefront. This custom-built residence features an open floor plan with vaulted ceilings, floor-to-ceiling windows, and multiple decks overlooking the lake. The gourmet kitchen features top-of-the-line appliances and opens to a great room with stone fireplace. The master suite offers lake views, spa bathroom, and private deck. Outdoor amenities include a private dock with boat house, outdoor kitchen and dining area, fire pit, and beautifully landscaped grounds with mature pines.",
    yearBuilt: 2020,
    lotSize: 21000,
    propertyType: "Lakefront Home",
    gallery: [
      "/luxury-lakefront-home.jpg",
      "/beachfront-luxury-villa.jpg",
      "/luxury-modern-mansion-pool.png",
    ],
    featured: true,
  },
  {
    id: 7,
    name: "The Meridian Estate 7",
    address: "1847 Pacific Heights Boulevard, San Francisco, CA",
    price: 8750000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    image: "/luxury-modern-mansion-pool.png",
    features: ["Ocean View", "Wine Cellar", "Home Theater"],
    description:
      "An architectural masterpiece perched atop Pacific Heights, The Meridian Estate offers breathtaking panoramic views of the San Francisco Bay and Golden Gate Bridge. This stunning contemporary residence features floor-to-ceiling windows, a gourmet chef's kitchen with top-of-the-line appliances, and a luxurious master suite with spa-like bathroom. The lower level boasts an impressive wine cellar, state-of-the-art home theater, and fitness center. Outdoor living spaces include multiple terraces, an infinity pool, and meticulously landscaped gardens.",
    yearBuilt: 2020,
    lotSize: 12000,
    propertyType: "Single Family Home",
    gallery: [
      "/luxury-modern-mansion-pool.png",
      "/luxury-estate-with-gardens.jpg",
      "/luxury-penthouse-city-view.jpg",
    ],
    featured: false,
  },
  {
    id: 8,
    name: "The Meridian Estate 8",
    address: "1847 Pacific Heights Boulevard, San Francisco, CA",
    price: 8750000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    image: "/luxury-modern-mansion-pool.png",
    features: ["Ocean View", "Wine Cellar", "Home Theater"],
    description:
      "An architectural masterpiece perched atop Pacific Heights, The Meridian Estate offers breathtaking panoramic views of the San Francisco Bay and Golden Gate Bridge. This stunning contemporary residence features floor-to-ceiling windows, a gourmet chef's kitchen with top-of-the-line appliances, and a luxurious master suite with spa-like bathroom. The lower level boasts an impressive wine cellar, state-of-the-art home theater, and fitness center. Outdoor living spaces include multiple terraces, an infinity pool, and meticulously landscaped gardens.",
    yearBuilt: 2020,
    lotSize: 12000,
    propertyType: "Single Family Home",
    gallery: [
      "/luxury-modern-mansion-pool.png",
      "/luxury-estate-with-gardens.jpg",
      "/luxury-penthouse-city-view.jpg",
    ],
    featured: false,
  },
  {
    id: 9,
    name: "The Meridian Estate 9",
    address: "1847 Pacific Heights Boulevard, San Francisco, CA",
    price: 8750000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    image: "/luxury-modern-mansion-pool.png",
    features: ["Ocean View", "Wine Cellar", "Home Theater"],
    description:
      "An architectural masterpiece perched atop Pacific Heights, The Meridian Estate offers breathtaking panoramic views of the San Francisco Bay and Golden Gate Bridge. This stunning contemporary residence features floor-to-ceiling windows, a gourmet chef's kitchen with top-of-the-line appliances, and a luxurious master suite with spa-like bathroom. The lower level boasts an impressive wine cellar, state-of-the-art home theater, and fitness center. Outdoor living spaces include multiple terraces, an infinity pool, and meticulously landscaped gardens.",
    yearBuilt: 2020,
    lotSize: 12000,
    propertyType: "Single Family Home",
    gallery: [
      "/luxury-modern-mansion-pool.png",
      "/luxury-estate-with-gardens.jpg",
      "/luxury-penthouse-city-view.jpg",
    ],
    featured: true,
  },
  {
    id: 10,
    name: "The Meridian Estate 10",
    address: "1847 Pacific Heights Boulevard, San Francisco, CA",
    price: 8750000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    image: "/luxury-modern-mansion-pool.png",
    features: ["Ocean View", "Wine Cellar", "Home Theater"],
    description:
      "An architectural masterpiece perched atop Pacific Heights, The Meridian Estate offers breathtaking panoramic views of the San Francisco Bay and Golden Gate Bridge. This stunning contemporary residence features floor-to-ceiling windows, a gourmet chef's kitchen with top-of-the-line appliances, and a luxurious master suite with spa-like bathroom. The lower level boasts an impressive wine cellar, state-of-the-art home theater, and fitness center. Outdoor living spaces include multiple terraces, an infinity pool, and meticulously landscaped gardens.",
    yearBuilt: 2020,
    lotSize: 12000,
    propertyType: "Single Family Home",
    gallery: [
      "/luxury-modern-mansion-pool.png",
      "/luxury-estate-with-gardens.jpg",
      "/luxury-penthouse-city-view.jpg",
    ],
    featured: true,
  },
  {
    id: 11,
    name: "The Meridian Estate 11",
    address: "1847 Pacific Heights Boulevard, San Francisco, CA",
    price: 8750000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    image: "/luxury-modern-mansion-pool.png",
    features: ["Ocean View", "Wine Cellar", "Home Theater"],
    description:
      "An architectural masterpiece perched atop Pacific Heights, The Meridian Estate offers breathtaking panoramic views of the San Francisco Bay and Golden Gate Bridge. This stunning contemporary residence features floor-to-ceiling windows, a gourmet chef's kitchen with top-of-the-line appliances, and a luxurious master suite with spa-like bathroom. The lower level boasts an impressive wine cellar, state-of-the-art home theater, and fitness center. Outdoor living spaces include multiple terraces, an infinity pool, and meticulously landscaped gardens.",
    yearBuilt: 2020,
    lotSize: 12000,
    propertyType: "Single Family Home",
    gallery: [
      "/luxury-modern-mansion-pool.png",
      "/luxury-estate-with-gardens.jpg",
      "/luxury-penthouse-city-view.jpg",
    ],
    featured: false,
  },
  {
    id: 12,
    name: "The Meridian Estate 12",
    address: "1847 Pacific Heights Boulevard, San Francisco, CA",
    price: 8750000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    image: "/luxury-modern-mansion-pool.png",
    features: ["Ocean View", "Wine Cellar", "Home Theater"],
    description:
      "An architectural masterpiece perched atop Pacific Heights, The Meridian Estate offers breathtaking panoramic views of the San Francisco Bay and Golden Gate Bridge. This stunning contemporary residence features floor-to-ceiling windows, a gourmet chef's kitchen with top-of-the-line appliances, and a luxurious master suite with spa-like bathroom. The lower level boasts an impressive wine cellar, state-of-the-art home theater, and fitness center. Outdoor living spaces include multiple terraces, an infinity pool, and meticulously landscaped gardens.",
    yearBuilt: 2020,
    lotSize: 12000,
    propertyType: "Single Family Home",
    gallery: [
      "/luxury-modern-mansion-pool.png",
      "/luxury-estate-with-gardens.jpg",
      "/luxury-penthouse-city-view.jpg",
    ],
    featured: true,
  },
  {
    id: 13,
    name: "The Meridian Estate 13",
    address: "1847 Pacific Heights Boulevard, San Francisco, CA",
    price: 8750000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    image: "/luxury-modern-mansion-pool.png",
    features: ["Ocean View", "Wine Cellar", "Home Theater"],
    description:
      "An architectural masterpiece perched atop Pacific Heights, The Meridian Estate offers breathtaking panoramic views of the San Francisco Bay and Golden Gate Bridge. This stunning contemporary residence features floor-to-ceiling windows, a gourmet chef's kitchen with top-of-the-line appliances, and a luxurious master suite with spa-like bathroom. The lower level boasts an impressive wine cellar, state-of-the-art home theater, and fitness center. Outdoor living spaces include multiple terraces, an infinity pool, and meticulously landscaped gardens.",
    yearBuilt: 2020,
    lotSize: 12000,
    propertyType: "Single Family Home",
    gallery: [
      "/luxury-modern-mansion-pool.png",
      "/luxury-estate-with-gardens.jpg",
      "/luxury-penthouse-city-view.jpg",
    ],
    featured: true,
  },
  {
    id: 14,
    name: "The Meridian Estate 14",
    address: "1847 Pacific Heights Boulevard, San Francisco, CA",
    price: 8750000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    image: "/luxury-penthouse-city-view.jpg",
    features: ["Ocean View", "Wine Cellar", "Home Theater"],
    description:
      "An architectural masterpiece perched atop Pacific Heights, The Meridian Estate offers breathtaking panoramic views of the San Francisco Bay and Golden Gate Bridge. This stunning contemporary residence features floor-to-ceiling windows, a gourmet chef's kitchen with top-of-the-line appliances, and a luxurious master suite with spa-like bathroom. The lower level boasts an impressive wine cellar, state-of-the-art home theater, and fitness center. Outdoor living spaces include multiple terraces, an infinity pool, and meticulously landscaped gardens.",
    yearBuilt: 2020,
    lotSize: 12000,
    propertyType: "Single Family Home",
    gallery: [
      "/luxury-modern-mansion-pool.png",
      "/luxury-estate-with-gardens.jpg",
      "/luxury-penthouse-city-view.jpg",
    ],
    featured: true,
  },
  {
    id: 15,
    name: "The Meridian Estate 15",
    address: "1847 Pacific Heights Boulevard, San Francisco, CA",
    price: 8750000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    image: "/luxury-estate-with-gardens.jpg",
    features: ["Ocean View", "Wine Cellar", "Home Theater"],
    description:
      "An architectural masterpiece perched atop Pacific Heights, The Meridian Estate offers breathtaking panoramic views of the San Francisco Bay and Golden Gate Bridge. This stunning contemporary residence features floor-to-ceiling windows, a gourmet chef's kitchen with top-of-the-line appliances, and a luxurious master suite with spa-like bathroom. The lower level boasts an impressive wine cellar, state-of-the-art home theater, and fitness center. Outdoor living spaces include multiple terraces, an infinity pool, and meticulously landscaped gardens.",
    yearBuilt: 2020,
    lotSize: 12000,
    propertyType: "Single Family Home",
    gallery: [
      "/luxury-modern-mansion-pool.png",
      "/luxury-estate-with-gardens.jpg",
      "/luxury-penthouse-city-view.jpg",
    ],
    featured: true,
  },
  {
    id: 16,
    name: "The Meridian Estate 16",
    address: "1847 Pacific Heights Boulevard, San Francisco, CA",
    price: 8750000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    image: "/luxury-modern-mansion-pool.png",
    features: ["Ocean View", "Wine Cellar", "Home Theater"],
    description:
      "An architectural masterpiece perched atop Pacific Heights, The Meridian Estate offers breathtaking panoramic views of the San Francisco Bay and Golden Gate Bridge. This stunning contemporary residence features floor-to-ceiling windows, a gourmet chef's kitchen with top-of-the-line appliances, and a luxurious master suite with spa-like bathroom. The lower level boasts an impressive wine cellar, state-of-the-art home theater, and fitness center. Outdoor living spaces include multiple terraces, an infinity pool, and meticulously landscaped gardens.",
    yearBuilt: 2020,
    lotSize: 12000,
    propertyType: "Single Family Home",
    gallery: [
      "/luxury-modern-mansion-pool.png",
      "/luxury-estate-with-gardens.jpg",
      "/luxury-penthouse-city-view.jpg",
    ],
    featured: false,
  },
  {
    id: 17,
    name: "The Meridian Estate 17",
    address: "1847 Pacific Heights Boulevard, San Francisco, CA",
    price: 8750000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    image: "/luxury-modern-mansion-pool.png",
    features: ["Ocean View", "Wine Cellar", "Home Theater"],
    description:
      "An architectural masterpiece perched atop Pacific Heights, The Meridian Estate offers breathtaking panoramic views of the San Francisco Bay and Golden Gate Bridge. This stunning contemporary residence features floor-to-ceiling windows, a gourmet chef's kitchen with top-of-the-line appliances, and a luxurious master suite with spa-like bathroom. The lower level boasts an impressive wine cellar, state-of-the-art home theater, and fitness center. Outdoor living spaces include multiple terraces, an infinity pool, and meticulously landscaped gardens.",
    yearBuilt: 2020,
    lotSize: 12000,
    propertyType: "Single Family Home",
    gallery: [
      "/luxury-modern-mansion-pool.png",
      "/luxury-estate-with-gardens.jpg",
      "/luxury-penthouse-city-view.jpg",
    ],
    featured: true,
  },
  {
    id: 18,
    name: "The Meridian Estate 18",
    address: "1847 Pacific Heights Boulevard, San Francisco, CA",
    price: 8750000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8500,
    image: "/luxury-modern-mansion-pool.png",
    features: ["Ocean View", "Wine Cellar", "Home Theater"],
    description:
      "An architectural masterpiece perched atop Pacific Heights, The Meridian Estate offers breathtaking panoramic views of the San Francisco Bay and Golden Gate Bridge. This stunning contemporary residence features floor-to-ceiling windows, a gourmet chef's kitchen with top-of-the-line appliances, and a luxurious master suite with spa-like bathroom. The lower level boasts an impressive wine cellar, state-of-the-art home theater, and fitness center. Outdoor living spaces include multiple terraces, an infinity pool, and meticulously landscaped gardens.",
    yearBuilt: 2020,
    lotSize: 12000,
    propertyType: "Single Family Home",
    gallery: [
      "/luxury-modern-mansion-pool.png",
      "/luxury-estate-with-gardens.jpg",
      "/luxury-penthouse-city-view.jpg",
    ],
    featured: false,
  },
];
